language: objective-c
xcode_sdk: 7.1
notifications:
  email: true
  slack:
    secure: E1at9Fi4d2eLagKInwGOfvvcSr8rrVti+N3HzvlcL9UcYavwzfAstMX/nXoHTl8LR5/Dh4Sdja2+NeJp2uVNwlK7aVKk5egQ8q6qAEmcXlWgjqyyTusB1lgiaOQnbOuqsntg/3X5sP8nz5+V3sggelPnOrVwNCCkVXXSff2SHhE=
rvm:
- 2.1.1
branches:
  only:
  - master
  - "/with\\-ci$/"
git:
  submodules: false
env:
  global:
  - SAUCE_REST_ROOT=https://saucelabs.com/rest/v1
  - APPIUM_HOST=ondemand.saucelabs.com
  - APPIUM_PORT=80
  - SAUCE_USERNAME=dylanatsauce
  - IOS_CONCURRENCY=30
  - ANDROID_CONCURRENCY=30
  - SELENDROID_CONCURRENCY=10
  - GAPPIUM_CONCURRENCY=10
  - secure: "Wr4Xg957CXl06wovfAgEb8FvraYpK4c385KmO4TvOEv6+12H87lD1m7QNXeBM8GFwxAULm7bc1KBO5hcdGTUtsz5Y0MOZJrkpmv2lbiyX0SAoYBI2jJ+JcwYSl2NiSPI3qUVWxm8o2O9mGA3rCAcY6nHOSX1tX6RRmVfRRhvHws="
  - HTTP_RETRIES=5
  - HTTP_RETRY_DELAY=5000
  - DEBUG_CONNECTION=1
  - MOCHA_INIT_TIMEOUT=600000
  - LAUNCH_TIMEOUT='{"global":90000,"afterSimLaunch":30000}'
  matrix:
  - CI_CONFIG=unit
  - CI_CONFIG=android
  - CI_CONFIG=ios
  - CI_CONFIG=gappium
  - CI_CONFIG=selendroid
before_script:
- gem install --no-rdoc --no-ri appium_doc_lint
- "./ci/installers/install-node.sh"
- 'echo Node.js version: `node -v`'
- npm install -g jshint grunt-cli mocha
- npm install
- "./ci/installers/install-sauce-connect.sh"
- "./ci/before_script_extra.sh"
- "ulimit -n 8000"
# disabling sauce-connect until travis ichef issue is sorted
# - "./ci/start-sauce-connect.sh"
script:
- "./ci/script.sh"
- bash -c 'while true; do ping ondemand.saucelabs.com &> /dev/null; sleep 10; done' &
